/* Layout do not present for this BSP */
#include "stm32wlxx_hal.h"

#define __PAGE_INDEX_TO_ARRD(index) ((index)*FLASH_PAGE_SIZE + FLASH_BASE)
#define __PAGE_COUNT_TO_SIZE(count) ((count)*FLASH_PAGE_SIZE)
#define __BYTES_TO_KILOBYTES(bytes) ((bytes) / 1024)

#define FLASH_BLDR_PAGE_INDEX (0)
#define FLASH_BLDR_PAGE_ADDR  __PAGE_INDEX_TO_ARRD(FLASH_BLDR_PAGE_INDEX)
#define FLASH_BLDR_PAGE_COUNT (32U * 1024U / FLASH_PAGE_SIZE)
#define FLASH_BLDR_SIZE       __PAGE_COUNT_TO_SIZE(FLASH_BLDR_PAGE_COUNT)

#define FLASH_APP_PAGE_INDEX (FLASH_BLDR_PAGE_COUNT)
#define FLASH_APP_PAGE_ADDR  __PAGE_INDEX_TO_ARRD(FLASH_APP_PAGE_INDEX)
#define FLASH_APP_PAGE_COUNT                                                                 \
    (128 - FLASH_BLDR_PAGE_COUNT - FLASH_SETTINGS_PAGE_COUNT - FLASH_GNSS_TRACE_PAGE_COUNT - \
     FLASH_LORAWAN_NVM_PAGE_COUNT)
#define FLASH_APP_PAGE_SIZE __PAGE_COUNT_TO_SIZE(FLASH_APP_PAGE_COUNT)

#define FLASH_LORAWAN_NVM_PAGE_INDEX (FLASH_GNSS_TRACE_PAGE_INDEX - 1U)
#define FLASH_LORAWAN_NVM_PAGE_ADDR  __PAGE_INDEX_TO_ARRD(FLASH_LORAWAN_NVM_PAGE_INDEX)
#define FLASH_LORAWAN_NVM_PAGE_COUNT (1U)
#define FLASH_LORAWAN_NVM_PAGE_SIZE  __PAGE_COUNT_TO_SIZE(FLASH_LORAWAN_NVM_PAGE_COUNT)

#define FLASH_GNSS_TRACE_PAGE_INDEX (FLASH_SETTINGS_PAGE_INDEX - FLASH_GNSS_TRACE_PAGE_COUNT)
#define FLASH_GNSS_TRACE_PAGE_ADDR  __PAGE_INDEX_TO_ARRD(FLASH_GNSS_TRACE_PAGE_INDEX)
#define FLASH_GNSS_TRACE_PAGE_COUNT (2U)
#define FLASH_GNSS_TRACE_PAGE_SIZE  __PAGE_COUNT_TO_SIZE(FLASH_GNSS_TRACE_PAGE_COUNT)

#define FLASH_SETTINGS_PAGE_INDEX (FLASH_PAGE_NB - 1U)
#define FLASH_SETTINGS_PAGE_ADDR  __PAGE_INDEX_TO_ARRD(FLASH_SETTINGS_PAGE_INDEX)
#define FLASH_SETTINGS_PAGE_COUNT (1U)
#define FLASH_SETTINGS_PAGE_SIZE  __PAGE_COUNT_TO_SIZE(FLASH_SETTINGS_PAGE_COUNT)

#if CONFIG_BOOTLOADER_BUILD == 1
#    define TARGET_BASE_ADDR FLASH_BLDR_PAGE_ADDR
#else
#    define TARGET_BASE_ADDR FLASH_APP_PAGE_ADDR
#endif /* CONFIG_BOOTLOADER_BUILD */

#define BSP_CONF_APP_HEAP_SIZE  0
#define BSP_CONF_APP_STACK_SIZE 1280

#define BSP_CONF_BLDR_HEAP_SIZE  0
#define BSP_CONF_BLDR_STACK_SIZE 1280
